version: '2.1'
services:
  app:
    image: "opensalt/app:${COMMIT}"

  php:
    image: opensalt/php:7.3-fpm
    depends_on:
      - db
    environment:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_HOST: "${MYSQL_HOST:-db}"
      BRAND_LOGO_URL:
      BRAND_LOGO_STYLE:
      BRAND_LINK_URL:
      BRAND_LINK_STYLE:
      ALLOW_LOCAL_DEV: 'true'
      ALLOW_EXTERNAL_DEV_IPS:
      DEV_COOKIE:
    volumes_from:
      - app
    working_dir: /var/www/html

  nginx:
    image: opensalt/nginx:1.16-alpine
    depends_on:
      - php
    environment:
      UPSTREAM_HOST: php:9000
    volumes_from:
      - app
    working_dir: /var/www/html
    ports:
      - "${PORT:-4000}:80"
    #networks:
      #default:
        #proxy:
          #aliases:
            #- "${COMPOSE_PROJECT_NAME}-salt"

  db:
    image: percona:${MYSQL_VERSION}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/max_allowed_packet.cnf:/etc/mysql/conf.d/max_allowed_packet.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:

volumes:
  mysql-data:
    #external:
      #name: "${COMPOSE_PROJECT_NAME}-mysql-data"

#networks:
  #proxy:
    #external:
      #name: nginx-proxy
